export type Council = {
  name: string;
  country: "England" | "Scotland" | "Wales";
  region?: string;
  safeguardingUrl: string;
  phone?: string;
  outOfHoursPhone?: string;
};

// Safeguarding adults referral pages for every upper-tier / unitary authority
// across England, Scotland and Wales. Phone numbers are the main adult
// safeguarding line where published; verify locally before relying on them.
export const COUNCILS: Council[] = [
  // ===================== ENGLAND =====================
  // London boroughs
  { name: "Barking and Dagenham", country: "England", region: "London", safeguardingUrl: "https://www.lbbd.gov.uk/safeguarding-adults", phone: "020 8227 2915", outOfHoursPhone: "020 8594 8356" },
  { name: "Barnet", country: "England", region: "London", safeguardingUrl: "https://www.barnet.gov.uk/adult-social-care/safeguarding-adults", phone: "020 8359 5000" },
  { name: "Bexley", country: "England", region: "London", safeguardingUrl: "https://www.bexley.gov.uk/services/adult-social-care/safeguarding-adults", phone: "020 8303 7777" },
  { name: "Brent", country: "England", region: "London", safeguardingUrl: "https://www.brent.gov.uk/adult-social-care/safeguarding-adults", phone: "020 8937 4098" },
  { name: "Bromley", country: "England", region: "London", safeguardingUrl: "https://www.bromley.gov.uk/safeguarding-adults", phone: "020 8461 7777" },
  { name: "Camden", country: "England", region: "London", safeguardingUrl: "https://www.camden.gov.uk/safeguarding-adults", phone: "020 7974 4000" },
  { name: "City of London", country: "England", region: "London", safeguardingUrl: "https://www.cityoflondon.gov.uk/services/adult-social-care/safeguarding-adults", phone: "020 7332 1224" },
  { name: "Croydon", country: "England", region: "London", safeguardingUrl: "https://www.croydon.gov.uk/health-and-wellbeing/safeguarding/safeguarding-adults", phone: "020 8726 6500" },
  { name: "Ealing", country: "England", region: "London", safeguardingUrl: "https://www.ealing.gov.uk/info/201139/safeguarding_adults", phone: "020 8825 8000" },
  { name: "Enfield", country: "England", region: "London", safeguardingUrl: "https://new.enfield.gov.uk/services/adult-social-care/safeguarding-adults/", phone: "020 8379 1000" },
  { name: "Greenwich", country: "England", region: "London", safeguardingUrl: "https://www.royalgreenwich.gov.uk/info/200229/safeguarding_adults", phone: "020 8921 2304" },
  { name: "Hackney", country: "England", region: "London", safeguardingUrl: "https://hackney.gov.uk/safeguarding-adults", phone: "020 8356 5782" },
  { name: "Hammersmith and Fulham", country: "England", region: "London", safeguardingUrl: "https://www.lbhf.gov.uk/articles/health-and-adult-social-care/safeguarding-adults", phone: "020 8753 4198" },
  { name: "Haringey", country: "England", region: "London", safeguardingUrl: "https://www.haringey.gov.uk/social-care-and-health/safeguarding-adults", phone: "020 8489 1400" },
  { name: "Harrow", country: "England", region: "London", safeguardingUrl: "https://www.harrow.gov.uk/social-care-health/safeguarding-adults", phone: "020 8901 2680" },
  { name: "Havering", country: "England", region: "London", safeguardingUrl: "https://www.havering.gov.uk/info/20011/adult_social_care/85/safeguarding_adults", phone: "01708 432 824" },
  { name: "Hillingdon", country: "England", region: "London", safeguardingUrl: "https://www.hillingdon.gov.uk/safeguarding-adults", phone: "01895 556 633" },
  { name: "Hounslow", country: "England", region: "London", safeguardingUrl: "https://www.hounslow.gov.uk/info/20039/adult_social_care/107/safeguarding_adults", phone: "020 8583 3100" },
  { name: "Islington", country: "England", region: "London", safeguardingUrl: "https://www.islington.gov.uk/social-care-and-health/safeguarding-adults", phone: "020 7527 2299" },
  { name: "Kensington and Chelsea", country: "England", region: "London", safeguardingUrl: "https://www.rbkc.gov.uk/health-and-social-care/safeguarding-adults", phone: "020 7361 3013" },
  { name: "Kingston upon Thames", country: "England", region: "London", safeguardingUrl: "https://www.kingston.gov.uk/health-social-care/safeguarding-adults", phone: "020 8547 5005" },
  { name: "Lambeth", country: "England", region: "London", safeguardingUrl: "https://www.lambeth.gov.uk/adult-social-care-and-health/safeguarding-adults", phone: "020 7926 5555" },
  { name: "Lewisham", country: "England", region: "London", safeguardingUrl: "https://lewisham.gov.uk/myservices/socialcare/adult-protection", phone: "020 8314 7777" },
  { name: "Merton", country: "England", region: "London", safeguardingUrl: "https://www.merton.gov.uk/health-social-care/adultsocialcare/adultsafeguarding", phone: "020 8545 4388" },
  { name: "Newham", country: "England", region: "London", safeguardingUrl: "https://www.newham.gov.uk/health-adult-social-care/safeguarding-adults", phone: "020 8430 2000" },
  { name: "Redbridge", country: "England", region: "London", safeguardingUrl: "https://www.redbridge.gov.uk/adult-social-care/safeguarding-adults/", phone: "020 8708 7333" },
  { name: "Richmond upon Thames", country: "England", region: "London", safeguardingUrl: "https://www.richmond.gov.uk/services/adult_social_care/safeguarding_adults", phone: "020 8891 7971" },
  { name: "Southwark", country: "England", region: "London", safeguardingUrl: "https://www.southwark.gov.uk/health-and-wellbeing/adult-safeguarding", phone: "020 7525 3324" },
  { name: "Sutton", country: "England", region: "London", safeguardingUrl: "https://www.sutton.gov.uk/info/200377/safeguarding_adults", phone: "020 8770 5000" },
  { name: "Tower Hamlets", country: "England", region: "London", safeguardingUrl: "https://www.towerhamlets.gov.uk/lgnl/health__social_care/adult_social_care/safeguarding_adults", phone: "020 7364 5005" },
  { name: "Waltham Forest", country: "England", region: "London", safeguardingUrl: "https://www.walthamforest.gov.uk/adult-social-care/safeguarding-adults", phone: "020 8496 3000" },
  { name: "Wandsworth", country: "England", region: "London", safeguardingUrl: "https://www.wandsworth.gov.uk/health-and-social-care/adult-social-care/safeguarding-adults/", phone: "020 8871 7707" },
  { name: "Westminster", country: "England", region: "London", safeguardingUrl: "https://www.westminster.gov.uk/health-and-social-care/safeguarding-adults", phone: "020 7641 1444" },

  // English counties (upper tier)
  { name: "Bedford", country: "England", region: "East of England", safeguardingUrl: "https://www.bedford.gov.uk/health-and-social-care/safeguarding-adults", phone: "01234 276222" },
  { name: "Cambridgeshire", country: "England", region: "East of England", safeguardingUrl: "https://www.cambridgeshire.gov.uk/residents/adults/report-a-concern-about-an-adult", phone: "0345 045 5202" },
  { name: "Central Bedfordshire", country: "England", region: "East of England", safeguardingUrl: "https://www.centralbedfordshire.gov.uk/info/27/adult_social_care/172/report_abuse_of_an_adult", phone: "0300 300 8122" },
  { name: "Essex", country: "England", region: "East of England", safeguardingUrl: "https://www.essex.gov.uk/report-abuse-against-adult", phone: "0345 603 7634" },
  { name: "Hertfordshire", country: "England", region: "East of England", safeguardingUrl: "https://www.hertfordshire.gov.uk/services/adult-social-services/report-a-concern-about-an-adult/report-a-concern-about-an-adult.aspx", phone: "0300 123 4042" },
  { name: "Luton", country: "England", region: "East of England", safeguardingUrl: "https://m.luton.gov.uk/Page/Show/Health_and_social_care/adult_social_care/safeguarding_adults", phone: "01582 547 730" },
  { name: "Norfolk", country: "England", region: "East of England", safeguardingUrl: "https://www.norfolk.gov.uk/safety/safeguarding-adults", phone: "0344 800 8020" },
  { name: "Peterborough", country: "England", region: "East of England", safeguardingUrl: "https://www.peterborough.gov.uk/residents/adults/report-a-concern-about-an-adult", phone: "01733 747474" },
  { name: "Southend-on-Sea", country: "England", region: "East of England", safeguardingUrl: "https://www.southend.gov.uk/safeguarding-adults", phone: "01702 215008" },
  { name: "Suffolk", country: "England", region: "East of England", safeguardingUrl: "https://www.suffolk.gov.uk/care-and-support-for-adults/protecting-people-at-risk-of-abuse/safeguarding-adults", phone: "0808 800 4005" },
  { name: "Thurrock", country: "England", region: "East of England", safeguardingUrl: "https://www.thurrock.gov.uk/safeguarding-adults", phone: "01375 511 000" },

  { name: "Derby", country: "England", region: "East Midlands", safeguardingUrl: "https://www.derby.gov.uk/health-and-social-care/safeguarding-adults/", phone: "01332 640777" },
  { name: "Derbyshire", country: "England", region: "East Midlands", safeguardingUrl: "https://www.derbyshire.gov.uk/social-health/adult-care-and-wellbeing/safeguarding-adults/safeguarding-adults.aspx", phone: "01629 533190" },
  { name: "Leicester", country: "England", region: "East Midlands", safeguardingUrl: "https://www.leicester.gov.uk/health-and-social-care/help-for-adults/safeguarding-adults/", phone: "0116 454 1004" },
  { name: "Leicestershire", country: "England", region: "East Midlands", safeguardingUrl: "https://www.leicestershire.gov.uk/adult-social-care-and-health/safeguarding-vulnerable-adults", phone: "0116 305 0004" },
  { name: "Lincolnshire", country: "England", region: "East Midlands", safeguardingUrl: "https://www.lincolnshire.gov.uk/safeguarding-adults", phone: "01522 782155" },
  { name: "North Northamptonshire", country: "England", region: "East Midlands", safeguardingUrl: "https://www.northnorthants.gov.uk/adult-social-care/safeguarding-adults", phone: "0300 126 3001" },
  { name: "Nottingham", country: "England", region: "East Midlands", safeguardingUrl: "https://www.nottinghamcity.gov.uk/information-for-residents/health-and-social-care/adult-social-care/safeguarding-adults/", phone: "0300 131 0300" },
  { name: "Nottinghamshire", country: "England", region: "East Midlands", safeguardingUrl: "https://www.nottinghamshire.gov.uk/care/safeguarding/safeguarding-adults", phone: "0300 500 80 90" },
  { name: "Rutland", country: "England", region: "East Midlands", safeguardingUrl: "https://www.rutland.gov.uk/adult-social-care-health/adult-safeguarding", phone: "01572 758319" },
  { name: "West Northamptonshire", country: "England", region: "East Midlands", safeguardingUrl: "https://www.westnorthants.gov.uk/adult-social-care/safeguarding-adults", phone: "0300 126 7000" },

  { name: "County Durham", country: "England", region: "North East", safeguardingUrl: "https://www.durham.gov.uk/adultabuse", phone: "03000 267 979" },
  { name: "Darlington", country: "England", region: "North East", safeguardingUrl: "https://www.darlington.gov.uk/health-and-social-care/safeguarding-adults/", phone: "01325 406111" },
  { name: "Gateshead", country: "England", region: "North East", safeguardingUrl: "https://www.gateshead.gov.uk/article/2884/Safeguarding-adults", phone: "0191 433 7033" },
  { name: "Hartlepool", country: "England", region: "North East", safeguardingUrl: "https://www.hartlepool.gov.uk/safeguardingadults", phone: "01429 523390" },
  { name: "Middlesbrough", country: "England", region: "North East", safeguardingUrl: "https://www.middlesbrough.gov.uk/adult-social-care-and-health/adult-safeguarding/", phone: "01642 065070" },
  { name: "Newcastle upon Tyne", country: "England", region: "North East", safeguardingUrl: "https://www.newcastle.gov.uk/services/care-and-support/adults/safeguarding-adults", phone: "0191 278 8377" },
  { name: "North Tyneside", country: "England", region: "North East", safeguardingUrl: "https://my.northtyneside.gov.uk/category/859/safeguarding-adults", phone: "0191 643 2777" },
  { name: "Northumberland", country: "England", region: "North East", safeguardingUrl: "https://www.northumberland.gov.uk/Care/Support/Safeguarding-1.aspx", phone: "01670 536 400" },
  { name: "Redcar and Cleveland", country: "England", region: "North East", safeguardingUrl: "https://www.redcar-cleveland.gov.uk/health-and-social-care/safeguarding-adults", phone: "01642 065070" },
  { name: "South Tyneside", country: "England", region: "North East", safeguardingUrl: "https://www.southtyneside.gov.uk/article/35138/Report-adult-abuse", phone: "0191 424 6000" },
  { name: "Stockton-on-Tees", country: "England", region: "North East", safeguardingUrl: "https://www.stockton.gov.uk/adult-safeguarding", phone: "01642 527764" },
  { name: "Sunderland", country: "England", region: "North East", safeguardingUrl: "https://www.sunderland.gov.uk/article/12944/Adult-safeguarding", phone: "0191 520 5552" },

  { name: "Blackburn with Darwen", country: "England", region: "North West", safeguardingUrl: "https://www.blackburn.gov.uk/health-and-social-care/safeguarding-adults", phone: "01254 587547" },
  { name: "Blackpool", country: "England", region: "North West", safeguardingUrl: "https://www.blackpool.gov.uk/Residents/Health-and-social-care/Safeguarding/Safeguarding-adults.aspx", phone: "01253 477592" },
  { name: "Bolton", country: "England", region: "North West", safeguardingUrl: "https://www.bolton.gov.uk/safeguarding-adults", phone: "01204 337777" },
  { name: "Bury", country: "England", region: "North West", safeguardingUrl: "https://www.bury.gov.uk/adult-social-care/safeguarding-adults", phone: "0161 253 5151" },
  { name: "Cheshire East", country: "England", region: "North West", safeguardingUrl: "https://www.cheshireeast.gov.uk/livewell/staying-safe/adult-safeguarding/adult-safeguarding.aspx", phone: "0300 123 5010" },
  { name: "Cheshire West and Chester", country: "England", region: "North West", safeguardingUrl: "https://www.cheshirewestandchester.gov.uk/residents/health-and-social-care/safeguarding-adults", phone: "0300 123 7034" },
  { name: "Cumberland", country: "England", region: "North West", safeguardingUrl: "https://www.cumberland.gov.uk/adult-social-care/safeguarding-adults", phone: "0300 303 3589" },
  { name: "Halton", country: "England", region: "North West", safeguardingUrl: "https://www.halton.gov.uk/Pages/health/adultsocialcare/safeguardingadults.aspx", phone: "0151 907 8306" },
  { name: "Knowsley", country: "England", region: "North West", safeguardingUrl: "https://www.knowsley.gov.uk/residents/safeguarding/safeguarding-adults", phone: "0151 443 2600" },
  { name: "Lancashire", country: "England", region: "North West", safeguardingUrl: "https://www.lancashire.gov.uk/health-and-social-care/your-service-your-say/adult-safeguarding/", phone: "0300 123 6720" },
  { name: "Liverpool", country: "England", region: "North West", safeguardingUrl: "https://liverpool.gov.uk/communities-and-safety/safeguarding-adults/", phone: "0151 233 3800" },
  { name: "Manchester", country: "England", region: "North West", safeguardingUrl: "https://www.manchester.gov.uk/safeguardingadults", phone: "0161 234 5001" },
  { name: "Oldham", country: "England", region: "North West", safeguardingUrl: "https://www.oldham.gov.uk/info/200368/safeguarding/2118/safeguarding_adults", phone: "0161 770 7777" },
  { name: "Rochdale", country: "England", region: "North West", safeguardingUrl: "https://www.rochdale.gov.uk/health-and-wellbeing/safeguarding-adults", phone: "0300 303 8886" },
  { name: "Salford", country: "England", region: "North West", safeguardingUrl: "https://www.salford.gov.uk/health-and-social-care/safeguarding-adults/", phone: "0161 631 4777" },
  { name: "Sefton", country: "England", region: "North West", safeguardingUrl: "https://www.sefton.gov.uk/social-care/adults/adult-safeguarding/", phone: "0345 140 0845" },
  { name: "St Helens", country: "England", region: "North West", safeguardingUrl: "https://www.sthelens.gov.uk/article/5147/Safeguarding-adults", phone: "01744 676767" },
  { name: "Stockport", country: "England", region: "North West", safeguardingUrl: "https://www.stockport.gov.uk/safeguarding-adults", phone: "0161 217 6029" },
  { name: "Tameside", country: "England", region: "North West", safeguardingUrl: "https://www.tameside.gov.uk/safeguardingadults", phone: "0161 342 2400" },
  { name: "Trafford", country: "England", region: "North West", safeguardingUrl: "https://www.trafford.gov.uk/residents/health/safeguarding/Safeguarding-Adults.aspx", phone: "0161 912 5199" },
  { name: "Warrington", country: "England", region: "North West", safeguardingUrl: "https://www.warrington.gov.uk/safeguardingadults", phone: "01925 443322" },
  { name: "Westmorland and Furness", country: "England", region: "North West", safeguardingUrl: "https://www.westmorlandandfurness.gov.uk/adult-social-care/safeguarding-adults", phone: "0300 373 2890" },
  { name: "Wigan", country: "England", region: "North West", safeguardingUrl: "https://www.wigan.gov.uk/Resident/Health-Social-Care/Adults/Safeguarding/index.aspx", phone: "01942 828777" },
  { name: "Wirral", country: "England", region: "North West", safeguardingUrl: "https://www.wirral.gov.uk/health-and-social-care/safeguarding-adults", phone: "0151 514 2222" },

  { name: "Bracknell Forest", country: "England", region: "South East", safeguardingUrl: "https://www.bracknell-forest.gov.uk/health-and-social-care/safeguarding-adults", phone: "01344 351500" },
  { name: "Brighton and Hove", country: "England", region: "South East", safeguardingUrl: "https://www.brighton-hove.gov.uk/adult-social-care/safeguarding-adults", phone: "01273 295555" },
  { name: "Buckinghamshire", country: "England", region: "South East", safeguardingUrl: "https://www.buckinghamshire.gov.uk/social-care-and-health/safeguarding-adults-at-risk/", phone: "0800 137 915" },
  { name: "East Sussex", country: "England", region: "South East", safeguardingUrl: "https://www.eastsussex.gov.uk/social-care/adults/safeguarding", phone: "0345 60 80 191" },
  { name: "Hampshire", country: "England", region: "South East", safeguardingUrl: "https://www.hants.gov.uk/socialcareandhealth/adultsocialcare/safeguarding", phone: "0300 555 1386" },
  { name: "Isle of Wight", country: "England", region: "South East", safeguardingUrl: "https://www.iow.gov.uk/council/transparency-and-data/safeguarding-board/", phone: "01983 814980" },
  { name: "Kent", country: "England", region: "South East", safeguardingUrl: "https://www.kent.gov.uk/social-care-and-health/care-and-support/report-abuse", phone: "03000 41 61 61" },
  { name: "Medway", country: "England", region: "South East", safeguardingUrl: "https://www.medway.gov.uk/info/200158/adult_social_care/100/safeguarding_adults", phone: "01634 334 466" },
  { name: "Milton Keynes", country: "England", region: "South East", safeguardingUrl: "https://www.milton-keynes.gov.uk/health-and-social-care/safeguarding-adults", phone: "01908 253772" },
  { name: "Oxfordshire", country: "England", region: "South East", safeguardingUrl: "https://www.oxfordshire.gov.uk/residents/social-and-health-care/safeguarding-adults", phone: "0345 050 7666" },
  { name: "Portsmouth", country: "England", region: "South East", safeguardingUrl: "https://www.portsmouth.gov.uk/services/health-and-care/care-and-support-for-adults/safeguarding-adults/", phone: "023 9268 0810" },
  { name: "Reading", country: "England", region: "South East", safeguardingUrl: "https://www.reading.gov.uk/health-and-social-care/safeguarding/safeguarding-adults/", phone: "0118 937 3747" },
  { name: "Slough", country: "England", region: "South East", safeguardingUrl: "https://www.slough.gov.uk/adult-social-care/safeguarding-adults", phone: "01753 475111" },
  { name: "Southampton", country: "England", region: "South East", safeguardingUrl: "https://www.southampton.gov.uk/health-social-care/adults/safeguarding-adults/", phone: "023 8083 3003" },
  { name: "Surrey", country: "England", region: "South East", safeguardingUrl: "https://www.surreycc.gov.uk/social-care-and-health/concerned-for-someone/report-an-adult-at-risk", phone: "0300 470 9100" },
  { name: "West Berkshire", country: "England", region: "South East", safeguardingUrl: "https://info.westberks.gov.uk/safeguardingadults", phone: "01635 503050" },
  { name: "West Sussex", country: "England", region: "South East", safeguardingUrl: "https://www.westsussex.gov.uk/social-care-and-health/social-care-support/adult-safeguarding/", phone: "0330 222 4000" },
  { name: "Windsor and Maidenhead", country: "England", region: "South East", safeguardingUrl: "https://www.rbwm.gov.uk/home/health-and-social-care/safeguarding-adults", phone: "01628 683744" },
  { name: "Wokingham", country: "England", region: "South East", safeguardingUrl: "https://www.wokingham.gov.uk/health-and-social-care/safeguarding/safeguarding-adults", phone: "0118 974 6800" },

  { name: "Bath and North East Somerset", country: "England", region: "South West", safeguardingUrl: "https://www.bathnes.gov.uk/services/your-council-and-democracy/safer-communities/safeguarding-adults", phone: "01225 396000" },
  { name: "Bournemouth, Christchurch and Poole", country: "England", region: "South West", safeguardingUrl: "https://www.bcpcouncil.gov.uk/adultsocialcare/safeguarding-adults/safeguarding-adults", phone: "01202 123 654" },
  { name: "Bristol", country: "England", region: "South West", safeguardingUrl: "https://www.bristol.gov.uk/social-care-health/safeguarding-adults", phone: "0117 922 2700" },
  { name: "Cornwall", country: "England", region: "South West", safeguardingUrl: "https://www.cornwall.gov.uk/health-and-social-care/safeguarding-adults/", phone: "0300 1234 131" },
  { name: "Devon", country: "England", region: "South West", safeguardingUrl: "https://www.devon.gov.uk/care-and-health/adult-safeguarding/", phone: "0345 155 1007" },
  { name: "Dorset", country: "England", region: "South West", safeguardingUrl: "https://www.dorsetcouncil.gov.uk/care-and-support-for-adults/safeguarding-adults", phone: "01305 221016" },
  { name: "Gloucestershire", country: "England", region: "South West", safeguardingUrl: "https://www.gloucestershire.gov.uk/health-and-social-care/safeguarding-adults/", phone: "01452 426868" },
  { name: "Isles of Scilly", country: "England", region: "South West", safeguardingUrl: "https://www.scilly.gov.uk/health-wellbeing/adult-care/safeguarding-adults", phone: "01720 424462" },
  { name: "North Somerset", country: "England", region: "South West", safeguardingUrl: "https://www.n-somerset.gov.uk/my-services/adult-social-care-health/safeguarding-adults", phone: "01275 888 801" },
  { name: "Plymouth", country: "England", region: "South West", safeguardingUrl: "https://www.plymouth.gov.uk/safeguarding-adults", phone: "01752 668000" },
  { name: "Somerset", country: "England", region: "South West", safeguardingUrl: "https://www.somerset.gov.uk/social-care-and-health/safeguarding-adults/", phone: "0300 123 2224" },
  { name: "South Gloucestershire", country: "England", region: "South West", safeguardingUrl: "https://beta.southglos.gov.uk/safeguarding-adults", phone: "01454 868007" },
  { name: "Swindon", country: "England", region: "South West", safeguardingUrl: "https://www.swindon.gov.uk/info/20065/adult_social_care/337/safeguarding_adults", phone: "01793 463555" },
  { name: "Torbay", country: "England", region: "South West", safeguardingUrl: "https://www.torbay.gov.uk/social-care/safeguarding/adults/", phone: "01803 219700" },
  { name: "Wiltshire", country: "England", region: "South West", safeguardingUrl: "https://www.wiltshire.gov.uk/article/1019/Safeguarding-adults", phone: "0300 456 0111" },

  { name: "Birmingham", country: "England", region: "West Midlands", safeguardingUrl: "https://www.birmingham.gov.uk/info/50011/adult_social_care/2057/safeguarding_adults", phone: "0121 303 1234" },
  { name: "Coventry", country: "England", region: "West Midlands", safeguardingUrl: "https://www.coventry.gov.uk/safeguarding-adults", phone: "024 7683 3003" },
  { name: "Dudley", country: "England", region: "West Midlands", safeguardingUrl: "https://www.dudley.gov.uk/resident/care-health/adult-social-care/safeguarding-adults/", phone: "0300 555 0055" },
  { name: "Herefordshire", country: "England", region: "West Midlands", safeguardingUrl: "https://www.herefordshire.gov.uk/safeguarding/safeguarding-adults", phone: "01432 260101" },
  { name: "Sandwell", country: "England", region: "West Midlands", safeguardingUrl: "https://www.sandwell.gov.uk/adult-safeguarding", phone: "0845 352 2266" },
  { name: "Shropshire", country: "England", region: "West Midlands", safeguardingUrl: "https://www.shropshire.gov.uk/adult-social-care/keeping-safe/safeguarding-adults/", phone: "0345 678 9044" },
  { name: "Solihull", country: "England", region: "West Midlands", safeguardingUrl: "https://www.solihull.gov.uk/socialcareandhealth/safeguardingadults", phone: "0121 704 8007" },
  { name: "Staffordshire", country: "England", region: "West Midlands", safeguardingUrl: "https://www.staffordshire.gov.uk/Care-for-all-ages/Care-for-adults/Safeguarding/Safeguarding.aspx", phone: "0345 604 2719" },
  { name: "Stoke-on-Trent", country: "England", region: "West Midlands", safeguardingUrl: "https://www.stoke.gov.uk/info/20051/safeguarding/151/adult_safeguarding", phone: "0800 561 0015" },
  { name: "Telford and Wrekin", country: "England", region: "West Midlands", safeguardingUrl: "https://www.telford.gov.uk/info/20211/adult_safeguarding", phone: "01952 385385" },
  { name: "Walsall", country: "England", region: "West Midlands", safeguardingUrl: "https://go.walsall.gov.uk/adult_social_care/safeguarding_adults", phone: "0300 555 2922" },
  { name: "Warwickshire", country: "England", region: "West Midlands", safeguardingUrl: "https://www.warwickshire.gov.uk/safeguardingadults", phone: "01926 412080" },
  { name: "Wolverhampton", country: "England", region: "West Midlands", safeguardingUrl: "https://www.wolverhampton.gov.uk/adult-social-care/safeguarding-adults", phone: "01902 551199" },
  { name: "Worcestershire", country: "England", region: "West Midlands", safeguardingUrl: "https://www.worcestershire.gov.uk/council-services/adult-social-care/safeguarding-adults", phone: "01905 768053" },

  { name: "Barnsley", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.barnsley.gov.uk/services/adult-social-care/safeguarding-adults/", phone: "01226 773300" },
  { name: "Bradford", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.bradford.gov.uk/adult-social-care/safeguarding/safeguarding-adults/", phone: "01274 431077" },
  { name: "Calderdale", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.calderdale.gov.uk/v2/residents/health-and-social-care/adults/safeguarding-adults", phone: "01422 393000" },
  { name: "Doncaster", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.doncaster.gov.uk/services/adult-social-care/adult-safeguarding", phone: "01302 737777" },
  { name: "East Riding of Yorkshire", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.eastriding.gov.uk/living/safeguarding/safeguarding-adults/", phone: "01482 393939" },
  { name: "Kingston upon Hull", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.hull.gov.uk/health-and-wellbeing/safeguarding-adults", phone: "01482 616092" },
  { name: "Kirklees", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.kirklees.gov.uk/beta/adult-social-care-providers/safeguarding-adults.aspx", phone: "01484 414933" },
  { name: "Leeds", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.leeds.gov.uk/adult-social-care/safeguarding", phone: "0113 222 4401" },
  { name: "North East Lincolnshire", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.nelincs.gov.uk/health-wellbeing-and-adult-social-care/safeguarding-adults/", phone: "01472 256256" },
  { name: "North Lincolnshire", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.northlincs.gov.uk/people-health-and-care/safeguarding-adults/", phone: "01724 297000" },
  { name: "North Yorkshire", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.northyorks.gov.uk/health-and-social-care/safeguarding/safeguarding-adults", phone: "01609 780780" },
  { name: "Rotherham", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.rotherham.gov.uk/safeguarding-adults", phone: "01709 822330" },
  { name: "Sheffield", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.sheffield.gov.uk/care-support/safeguarding-adults", phone: "0114 273 4908" },
  { name: "Wakefield", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.wakefield.gov.uk/health-care-and-advice/adult-social-care/safeguarding-adults/", phone: "0345 8 503 503" },
  { name: "York", country: "England", region: "Yorkshire and the Humber", safeguardingUrl: "https://www.york.gov.uk/SafeguardingAdults", phone: "01904 555111" },

  // ===================== SCOTLAND =====================
  { name: "Aberdeen City", country: "Scotland", safeguardingUrl: "https://www.aberdeencity.gov.uk/services/health-social-care-and-community-wellbeing/adult-protection", phone: "0800 731 5520" },
  { name: "Aberdeenshire", country: "Scotland", safeguardingUrl: "https://www.aberdeenshire.gov.uk/social-care-and-health/social-work/adult-protection/", phone: "0800 731 5520" },
  { name: "Angus", country: "Scotland", safeguardingUrl: "https://www.angus.gov.uk/health_social_care_and_community_life/adult_protection", phone: "03452 777 778" },
  { name: "Argyll and Bute", country: "Scotland", safeguardingUrl: "https://www.argyll-bute.gov.uk/social-care-and-health/adult-care/adult-support-and-protection", phone: "01546 605517" },
  { name: "City of Edinburgh", country: "Scotland", safeguardingUrl: "https://www.edinburgh.gov.uk/social-care-health/adult-protection", phone: "0131 200 2324" },
  { name: "Clackmannanshire", country: "Scotland", safeguardingUrl: "https://www.clacks.gov.uk/social/adultprotection/", phone: "01259 225000" },
  { name: "Dumfries and Galloway", country: "Scotland", safeguardingUrl: "https://www.dumgal.gov.uk/article/15205/Adult-Support-and-Protection", phone: "030 33 33 3001" },
  { name: "Dundee City", country: "Scotland", safeguardingUrl: "https://www.dundeecity.gov.uk/service-area/social-work/adult-protection", phone: "01382 434019" },
  { name: "East Ayrshire", country: "Scotland", safeguardingUrl: "https://www.east-ayrshire.gov.uk/SocialCareAndHealth/AdultProtection/Adult-protection.aspx", phone: "01563 503000" },
  { name: "East Dunbartonshire", country: "Scotland", safeguardingUrl: "https://www.eastdunbarton.gov.uk/residents/health-and-social-care/adult-protection", phone: "0141 232 8200" },
  { name: "East Lothian", country: "Scotland", safeguardingUrl: "https://www.eastlothian.gov.uk/info/210570/adult_protection", phone: "01875 824309" },
  { name: "East Renfrewshire", country: "Scotland", safeguardingUrl: "https://www.eastrenfrewshire.gov.uk/adult-protection", phone: "0141 800 7850" },
  { name: "Falkirk", country: "Scotland", safeguardingUrl: "https://www.falkirk.gov.uk/services/social-care/protecting-people/adult-support-protection/", phone: "01324 506400" },
  { name: "Fife", country: "Scotland", safeguardingUrl: "https://www.fife.gov.uk/kb/docs/articles/social-care2/protecting-people/adult-protection", phone: "03451 55 15 03" },
  { name: "Glasgow City", country: "Scotland", safeguardingUrl: "https://www.glasgow.gov.uk/article/17273/Adult-Support-and-Protection", phone: "0141 287 0555" },
  { name: "Highland", country: "Scotland", safeguardingUrl: "https://www.highland.gov.uk/info/695/adult_care_and_support/178/adult_support_and_protection", phone: "0800 902 0042" },
  { name: "Inverclyde", country: "Scotland", safeguardingUrl: "https://www.inverclyde.gov.uk/social-care-and-health/adults-and-older-people/adult-protection", phone: "01475 715 365" },
  { name: "Midlothian", country: "Scotland", safeguardingUrl: "https://www.midlothian.gov.uk/info/200166/social_care/289/adult_protection", phone: "0131 271 3900" },
  { name: "Moray", country: "Scotland", safeguardingUrl: "https://www.moray.gov.uk/moray_standard/page_55590.html", phone: "0300 123 4566" },
  { name: "Na h-Eileanan Siar (Western Isles)", country: "Scotland", safeguardingUrl: "https://www.cne-siar.gov.uk/social-care-and-health/adult-support-and-protection/", phone: "01851 822708" },
  { name: "North Ayrshire", country: "Scotland", safeguardingUrl: "https://www.north-ayrshire.gov.uk/health-and-social-care-services/adult-protection.aspx", phone: "01294 310300" },
  { name: "North Lanarkshire", country: "Scotland", safeguardingUrl: "https://www.northlanarkshire.gov.uk/health-and-social-care/social-care/adult-protection", phone: "01698 332100" },
  { name: "Orkney Islands", country: "Scotland", safeguardingUrl: "https://www.orkney.gov.uk/Service-Directory/A/adult-protection.htm", phone: "01856 873535" },
  { name: "Perth and Kinross", country: "Scotland", safeguardingUrl: "https://www.pkc.gov.uk/article/17357/Adult-protection", phone: "0345 30 111 20" },
  { name: "Renfrewshire", country: "Scotland", safeguardingUrl: "https://www.renfrewshire.gov.uk/article/2786/Adult-protection", phone: "0300 300 1199" },
  { name: "Scottish Borders", country: "Scotland", safeguardingUrl: "https://www.scotborders.gov.uk/info/20015/social_care_and_health/100/adult_protection", phone: "0300 100 1800" },
  { name: "Shetland Islands", country: "Scotland", safeguardingUrl: "https://www.shetland.gov.uk/adult-protection", phone: "01595 744421" },
  { name: "South Ayrshire", country: "Scotland", safeguardingUrl: "https://www.south-ayrshire.gov.uk/adult-protection", phone: "0300 123 0900" },
  { name: "South Lanarkshire", country: "Scotland", safeguardingUrl: "https://www.southlanarkshire.gov.uk/info/200187/social_care/198/adult_protection", phone: "0303 123 1008" },
  { name: "Stirling", country: "Scotland", safeguardingUrl: "https://www.stirling.gov.uk/health-and-social-care/community-care/adult-protection/", phone: "0845 277 7000" },
  { name: "West Dunbartonshire", country: "Scotland", safeguardingUrl: "https://www.west-dunbarton.gov.uk/social-care-health/adult-protection/", phone: "01389 776499" },
  { name: "West Lothian", country: "Scotland", safeguardingUrl: "https://www.westlothian.gov.uk/article/2106/Adult-Protection", phone: "01506 281 234" },

  // ===================== WALES =====================
  { name: "Blaenau Gwent", country: "Wales", safeguardingUrl: "https://www.blaenau-gwent.gov.uk/en/resident/social-care/safeguarding/", phone: "01495 315700" },
  { name: "Bridgend", country: "Wales", safeguardingUrl: "https://www.bridgend.gov.uk/residents/social-care-and-wellbeing/safeguarding/", phone: "01656 642477" },
  { name: "Caerphilly", country: "Wales", safeguardingUrl: "https://www.caerphilly.gov.uk/Services/Social-services-and-wellbeing/Safeguarding", phone: "0808 100 2500" },
  { name: "Cardiff", country: "Wales", safeguardingUrl: "https://www.cardiff.gov.uk/ENG/resident/Social-Services-and-Wellbeing/Safeguarding-Adults/Pages/default.aspx", phone: "029 2053 6490" },
  { name: "Carmarthenshire", country: "Wales", safeguardingUrl: "https://www.carmarthenshire.gov.wales/home/council-services/social-care-health/safeguarding/", phone: "0300 333 2222" },
  { name: "Ceredigion", country: "Wales", safeguardingUrl: "https://www.ceredigion.gov.uk/resident/social-services/safeguarding/", phone: "01545 574000" },
  { name: "Conwy", country: "Wales", safeguardingUrl: "https://www.conwy.gov.uk/en/Resident/Social-Care-and-Wellbeing/Safeguarding/Safeguarding-adults.aspx", phone: "0300 456 1111" },
  { name: "Denbighshire", country: "Wales", safeguardingUrl: "https://www.denbighshire.gov.uk/en/health-and-social-care/safeguarding/safeguarding-adults.aspx", phone: "0300 456 1000" },
  { name: "Flintshire", country: "Wales", safeguardingUrl: "https://www.flintshire.gov.uk/en/Resident/Social-Services/Safeguarding.aspx", phone: "03000 858 858" },
  { name: "Gwynedd", country: "Wales", safeguardingUrl: "https://www.gwynedd.llyw.cymru/en/Residents/Health-and-social-care/Safeguarding/Safeguarding.aspx", phone: "01286 679 538" },
  { name: "Isle of Anglesey", country: "Wales", safeguardingUrl: "https://www.anglesey.gov.wales/en/Residents/Social-care-and-health/Safeguarding/Adults.aspx", phone: "01248 752752" },
  { name: "Merthyr Tydfil", country: "Wales", safeguardingUrl: "https://www.merthyr.gov.uk/resident/social-services/safeguarding/", phone: "01685 725000" },
  { name: "Monmouthshire", country: "Wales", safeguardingUrl: "https://www.monmouthshire.gov.uk/social-care-and-health/safeguarding/", phone: "01873 735573" },
  { name: "Neath Port Talbot", country: "Wales", safeguardingUrl: "https://www.npt.gov.uk/3034", phone: "01639 685767" },
  { name: "Newport", country: "Wales", safeguardingUrl: "https://www.newport.gov.uk/en/Care-Support/Safeguarding/Safeguarding.aspx", phone: "01633 656656" },
  { name: "Pembrokeshire", country: "Wales", safeguardingUrl: "https://www.pembrokeshire.gov.uk/safeguarding", phone: "01437 776056" },
  { name: "Powys", country: "Wales", safeguardingUrl: "https://en.powys.gov.uk/safeguarding", phone: "0345 602 7050" },
  { name: "Rhondda Cynon Taf", country: "Wales", safeguardingUrl: "https://www.rctcbc.gov.uk/EN/Resident/AdultsCommunityandCarers/Safeguarding/Safeguardingadults.aspx", phone: "01443 425003" },
  { name: "Swansea", country: "Wales", safeguardingUrl: "https://www.swansea.gov.uk/safeguardingadults", phone: "01792 636519" },
  { name: "Torfaen", country: "Wales", safeguardingUrl: "https://www.torfaen.gov.uk/en/HealthSocialCare/Safeguarding/Safeguarding.aspx", phone: "01495 762200" },
  { name: "Vale of Glamorgan", country: "Wales", safeguardingUrl: "https://www.valeofglamorgan.gov.uk/en/living/social_care/safeguarding/Safeguarding.aspx", phone: "01446 700111" },
  { name: "Wrexham", country: "Wales", safeguardingUrl: "https://www.wrexham.gov.uk/service/safeguarding-adults", phone: "0300 085 1101" },
];
