/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppFamilyRouteImport } from './routes/_app.family'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppResidentsIndexRouteImport } from './routes/_app.residents.index'
import { Route as AppCarePlansIndexRouteImport } from './routes/_app.care-plans.index'
import { Route as AppResidentsIdRouteImport } from './routes/_app.residents.$id'
import { Route as AppCarePlansIdRouteImport } from './routes/_app.care-plans.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyRoute = AppFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentsIndexRoute = AppResidentsIndexRouteImport.update({
  id: '/residents/',
  path: '/residents/',
  getParentRoute: () => AppRoute,
} as any)
const AppCarePlansIndexRoute = AppCarePlansIndexRouteImport.update({
  id: '/care-plans/',
  path: '/care-plans/',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentsIdRoute = AppResidentsIdRouteImport.update({
  id: '/residents/$id',
  path: '/residents/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCarePlansIdRoute = AppCarePlansIdRouteImport.update({
  id: '/care-plans/$id',
  path: '/care-plans/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/alerts': typeof AppAlertsRoute
  '/family': typeof AppFamilyRoute
  '/care-plans/$id': typeof AppCarePlansIdRoute
  '/residents/$id': typeof AppResidentsIdRoute
  '/care-plans/': typeof AppCarePlansIndexRoute
  '/residents/': typeof AppResidentsIndexRoute
}
export interface FileRoutesByTo {
  '/alerts': typeof AppAlertsRoute
  '/family': typeof AppFamilyRoute
  '/': typeof AppIndexRoute
  '/care-plans/$id': typeof AppCarePlansIdRoute
  '/residents/$id': typeof AppResidentsIdRoute
  '/care-plans': typeof AppCarePlansIndexRoute
  '/residents': typeof AppResidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/family': typeof AppFamilyRoute
  '/_app/': typeof AppIndexRoute
  '/_app/care-plans/$id': typeof AppCarePlansIdRoute
  '/_app/residents/$id': typeof AppResidentsIdRoute
  '/_app/care-plans/': typeof AppCarePlansIndexRoute
  '/_app/residents/': typeof AppResidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/family'
    | '/care-plans/$id'
    | '/residents/$id'
    | '/care-plans/'
    | '/residents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alerts'
    | '/family'
    | '/'
    | '/care-plans/$id'
    | '/residents/$id'
    | '/care-plans'
    | '/residents'
  id:
    | '__root__'
    | '/_app'
    | '/_app/alerts'
    | '/_app/family'
    | '/_app/'
    | '/_app/care-plans/$id'
    | '/_app/residents/$id'
    | '/_app/care-plans/'
    | '/_app/residents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/family': {
      id: '/_app/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AppFamilyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/residents/': {
      id: '/_app/residents/'
      path: '/residents'
      fullPath: '/residents/'
      preLoaderRoute: typeof AppResidentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/care-plans/': {
      id: '/_app/care-plans/'
      path: '/care-plans'
      fullPath: '/care-plans/'
      preLoaderRoute: typeof AppCarePlansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/residents/$id': {
      id: '/_app/residents/$id'
      path: '/residents/$id'
      fullPath: '/residents/$id'
      preLoaderRoute: typeof AppResidentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/care-plans/$id': {
      id: '/_app/care-plans/$id'
      path: '/care-plans/$id'
      fullPath: '/care-plans/$id'
      preLoaderRoute: typeof AppCarePlansIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppFamilyRoute: typeof AppFamilyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCarePlansIdRoute: typeof AppCarePlansIdRoute
  AppResidentsIdRoute: typeof AppResidentsIdRoute
  AppCarePlansIndexRoute: typeof AppCarePlansIndexRoute
  AppResidentsIndexRoute: typeof AppResidentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppFamilyRoute: AppFamilyRoute,
  AppIndexRoute: AppIndexRoute,
  AppCarePlansIdRoute: AppCarePlansIdRoute,
  AppResidentsIdRoute: AppResidentsIdRoute,
  AppCarePlansIndexRoute: AppCarePlansIndexRoute,
  AppResidentsIndexRoute: AppResidentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
