
ALTER TABLE public.residents
  ADD COLUMN IF NOT EXISTS dnacpr_status text,
  ADD COLUMN IF NOT EXISTS dnacpr_date date,
  ADD COLUMN IF NOT EXISTS dnacpr_notes text,
  ADD COLUMN IF NOT EXISTS marital_status text,
  ADD COLUMN IF NOT EXISTS residency_status text,
  ADD COLUMN IF NOT EXISTS admission_type text,
  ADD COLUMN IF NOT EXISTS discharge_date date,
  ADD COLUMN IF NOT EXISTS gender text,
  ADD COLUMN IF NOT EXISTS pronouns text,
  ADD COLUMN IF NOT EXISTS preferred_name text,
  ADD COLUMN IF NOT EXISTS religion text,
  ADD COLUMN IF NOT EXISTS ethnicity text,
  ADD COLUMN IF NOT EXISTS first_language text,
  ADD COLUMN IF NOT EXISTS nationality text,
  ADD COLUMN IF NOT EXISTS occupation_history text,
  ADD COLUMN IF NOT EXISTS funding_source text,
  ADD COLUMN IF NOT EXISTS local_authority text,
  ADD COLUMN IF NOT EXISTS gp_practice text,
  ADD COLUMN IF NOT EXISTS gp_phone text,
  ADD COLUMN IF NOT EXISTS allergies text,
  ADD COLUMN IF NOT EXISTS dietary_requirements text,
  ADD COLUMN IF NOT EXISTS communication_needs text,
  ADD COLUMN IF NOT EXISTS power_of_attorney text,
  ADD COLUMN IF NOT EXISTS advance_decisions text;
